steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia.gcr.io/$PROJECT_ID/rest-api-sample',
      '--cache-from', 'asia.gcr.io/$PROJECT_ID/rest-api-sample',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/rest-api-sample']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'rest-api-sample',
      '--image', 'asia.gcr.io/$PROJECT_ID/rest-api-sample',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
images:
  - 'asia.gcr.io/$PROJECT_ID/rest-api-sample'
