swagger: "2.0"
info:
  title: Echo Service
  description: This is HTTP echo service
  version: ""
host: 0.0.0.0:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /name/{name}:
    get:
      tags:
      - echo-service
      summary: echo-get echo-service
      operationId: echo-service#echo-get
      parameters:
      - name: age
        in: query
        description: Your age
        required: true
        type: integer
      - name: name
        in: path
        description: Your name
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /version:
    get:
      tags:
      - echo-service
      summary: version echo-service
      operationId: echo-service#version
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
